// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://croosqxagovnhdhktxkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyb29zcXhhZ292bmhkaGt0eGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MDc1NDcsImV4cCI6MjA1MzQ4MzU0N30.7AH5up2RFryGrzY0WJ1DeVCHGj42vfy8Xa5rZAIzXmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);